### ISSUE TITLE
Adding Videos into iatistandard.org

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Guidance#145]
Videos need to be linked into iatistandard.org. Suggest doing it in two ways:

i) Integrating links at relevant points (see my suggestions in this spreadsheet https://drive.google.com/open?id=1VjVxJvRlUtmel8K2XaDfjVRZkR3nE-YzpRREAZWA8HQ&authuser=0) 

ii) Creating a page in the guidance section, with a list of the videos (maybe by theme e.g. aidstream, registry, general queries, use of data etc.)

**Comment by amy-silcock** [comment]
This is no longer relevant, as there is a new IATI website: https://iatistandard.org/en/
