### ISSUE TITLE
Update links to :doc: type links in migration text

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Guidance#152]
The links in https://github.com/IATI/IATI-Guidance/blob/master/en/upgrades/integer-upgrade-to-2-01/migrating.rst need sorting out so that they are relative links and not hardwired

**Comment by caprenter** [comment]
@stevieflow I've removed the google links. Can you please check the internal links? Checkout the 152-update-links branch https://github.com/IATI/IATI-Guidance/tree/152-update-links to do your work perhaps.

**Comment by stevieflow** [comment]
Ok - I think it is about there now.  Needs a check viw PR https://github.com/IATI/IATI-Guidance/pull/194 , so will leave this issue open for now
