### ISSUE TITLE
Add internal links to migration document

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Guidance#161]
eg: 

> See Handling Translations

**Comment by caprenter** [comment]
I think this is waiting for clarification from @Bjwebb, therefore assigning it to him.

**Comment by Bjwebb** [comment]
No, this isn't correct. I've subsequently explained to @stevieflow how internal refs work in response to a separate issue, so assigning to him.

**Comment by stevieflow** [comment]
Currently, there is some markup in https://github.com/IATI/IATI-Guidance/blob/152-update-links/en/upgrades/integer-upgrade-to-2-01/migrating.rst#update-to-other-identifier-element:

> :ref:`Update to other-identifier element <#update-to-other-identifier-element>`

that tried to do this, but doesnt seem to work.  Any advice @caprenter @Bjwebb ?
