### ISSUE TITLE
Add guidance about requesting a code on the XI-IATI list

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Guidance#166]
From https://github.com/IATI/IATI-Schemas/issues/231

> Any publisher may request IATI to generate a code for it. This will be a manual process with a quick turnaround.

The process for this should be decided, and added as guidance.

**Comment by caprenter** [comment]
In practice, this 'process' means - contact IATI Support, and they will sort it out with you. Once an identifier has been agreed, it will be added to the IATI Organisation Identifier codelist: http://iatistandard.org/201/codelists/IATIOrganisationIdentifier/

The guidance for this should be displayed here:
http://iatistandard.org/201/organisation-identifiers/
http://iatistandard.org/105/organisation-identifiers/
http://iatistandard.org/104/organisation-identifiers/
http://iatistandard.org/103/getting-started/organisation-data/organisation-identifiers/
http://iatistandard.org/102/guides/organisation-data/organisation-identifiers/ 

The 2.01 source is here:
https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.01/en/organisation-identifiers.rst

It could be argued that in fact we don't need to take any action as on these pages it says, more than once, if you get stuck contact IATI Support.

N.B. Work on this issue should really take place in the https://github.com/IATI/IATI-Extra-Documentation repository.

**Comment by caprenter** [comment]
@stevieflow I think you might be able to review this and make a decision quite quickly.

**Comment by stevieflow** [comment]
@caprenter sorry - missed this.  Is there something I need to do, or could @iatisupport pick up?

**Comment by amy-silcock** [comment]
No further discussion has been had.
