### ISSUE TITLE
Include guidance on using XI-IATI

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Guidance#190]
Taken from https://github.com/IATI/IATI-Extra-Documentation/issues/267

**Comment by Bjwebb** [comment]
Different. From https://github.com/IATI/IATI-Extra-Documentation/issues/267 this issue is about:
> Specifically using XI-IATI to refer to a publisher who is not publishing to 2.01 yet, and whose organisation identifier in 1.0x is not valid in 2.01

Whereas https://github.com/IATI/IATI-Guidance/issues/166 is about requesting an organisation requesting a new XI-IATI identifier for itself.

**Comment by amy-silcock** [comment]
No further discussion has happened.
