### ISSUE TITLE
Implement "5. A consistent approach to organisation identifiers

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Guidance#191]
Moved from https://github.com/IATI/IATI-Extra-Documentation/issues/67

http://support.iatistandard.org/entries/41042267-Modify-DAC-derived-organisation-identifiers
- [x] 1) The OECD DAC is recognised as a registration agency with code XM-DAC.
- [ ] 2) DAC donor codes should be adopted 
- [ ] 3) DAC agency codes should be modified to be consistent with donor codes
- [ ] 4) DAC delivery channel codes should be prefixed with the DAC agency code.
- [ ] Additionally: IATI will put in place a cross-referencing utility to ease the pain for users of data.

**Comment by amy-silcock** [comment]
Org-id.guide are now leading on the creation of or ids. We are working with dac publishers to use the correct org ids.
