### ISSUE TITLE
Modify guidance on participating-org/@role

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Guidance#192]
Originally: https://github.com/IATI/IATI-Extra-Documentation/issues/258

Modify guidance on participating-org/@role : Definition of funding organisation http://support.iatistandard.org/entries/41583626-Modify-guidance-on-participating-org-role-Definition-of-funding-organisation

**Comment by amy-silcock** [comment]
Current descriptions can be found here: http://reference.iatistandard.org/202/codelists/OrganisationRole/
