### ISSUE TITLE
State that text/html is the appropriate format for a website on 2.01 migration page

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Guidance#199]
https://github.com/IATI/IATI-Guidance/blob/master/en/upgrades/integer-upgrade-to-2-01/migrating.rst#renamed-moved-and-removed-elements

`@format` is mandatory and the list http://iatistandard.org/201/codelists/FileFormat/ is too big to find the right match for the website, so it would be good to tell people in the migration doc what the correct format is.

**Comment by stevieflow** [comment]
Thanks.
