### ISSUE TITLE
Redirect Reference To DFID Minimum Requirements To gov.uk

### ISSUE THREAD

**Issue by iatisupport** [IATI/IATI-Guidance#204]
With the launch of the minimum requirements site on https://www.gov.uk/government/policies/making-uk-aid-more-open-and-transparent/supporting-pages/international-aid-transparency-initiative-publishing-requirements-for-partners-of-dfid we should remove the reference to the 'proposed' minimum requirements from http://iatistandard.org/201/guidance/how-to-publish/select-data-to-publish/ and replace with a link to gov.uk

**Comment by caprenter** [comment]
@iatisupport Please review on dev site and let me know if ready to go live

**Comment by iatisupport** [comment]
Reviewed on dev site and all okay to go live
