### ISSUE TITLE
Add Instructions For Process Of Changing A Publisher's Organisation Identifier

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Guidance#209]
The move to V2.01 highlighted the need for step by step guidance to guide a publisher through the process of changing their organisation identifier. Some guidance was provided as part of the V2.01 migration details (see http://iatistandard.org/201/upgrades/integer-upgrade-to-2-01/migrating/) but this information needs to exist for all versions

**Comment by amy-silcock** [comment]
Instructions can now be found here: https://iatistandard.org/en/guidance/preparing-organisation/organisation-account/updating-your-organisation-details/
