### ISSUE TITLE
Improve guidance by including more contextual examples and business cases

### ISSUE THREAD

**Issue by rory09** [IATI/IATI-Guidance#217]
A commenter on the IATI Standard version forums recently suggested that:

> [There should be] guidance on how to use the fields to answer a given question.  What was discussed briefly at the TAG was perhaps a series of notes organized by question, such as:
> - How can I find out whether a given activity may be on budget? (By looking at eg type of collaboration, type of aid, disbursement channel etc)
> - How can I filter activities to only have those implemented by CSOs? (By disbursement channel, type of organisation)
> 
> This is not about the standard per se, but about maximizing use of data.  A starting point may be to create a space where users could provide questions they struggle with, and where others could offer suggestions. The FAQ could be captured in How To notes.

This sounds like a very good idea, and may help to encourage more and more sophisticated use of IATI data, as well as help publishers be more confident about the fields they're publishing.

**Comment by amy-silcock** [comment]
Details on data use can now be found on the IATI website: https://iatistandard.org/en/using-data/. Guidance is to be written on different data use tools.

For now, no further work needed.
