### ISSUE TITLE
Guidance: Adding to the registry via API

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Guidance#24]
@iatisupport has flagged this article:

http://support.iatistandard.org/entries/20299306-Adding-to-the-registry-via-API

@Bjwebb is it relevant / useful?  We could add to the Registry API page, for example- or agree that this doesnt need transferring from the KB

**Comment by amy-silcock** [comment]
Instructions can be found here: https://iatistandard.org/en/guidance/publishing-data/publishing-files/how-to-publish-your-data-on-the-iati-registry-/
