### ISSUE TITLE
Introduction potentially contradicts Rules

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Guidance#244]
The [Key Considerations - Structured](http://iatistandard.org/202/introduction/key-considerations/structured/) page states that:

```
Format - IATI data should be formatted correctly as well-formed XML
Valid - IATI data should pass the relevant IATI schema validation
Rules - IATI data should satisfy the relevant Ruleset that provides additional conditions and logic.
```

The first two of these statements are not inline with the [activity](http://iatistandard.org/202/activity-standard/overview/activity-file/#considerations) and [org](http://iatistandard.org/202/organisation-standard/overview/organisation-file/#considerations) file Rules, which state that:

```
It must be well-formed XML.
It must validate against the relevant version of the IATI [organisation|activity] schema
```

Confusion is introduced because there is nothing (that I can locate) that states that Rules from Rulesets must be followed, while there is nothing to say that Rules defined outside Rulesets should not.

**Comment by hayfield** [comment]
https://github.com/IATI/IATI-Extra-Documentation/issues/334 notes that the below statements are prefixed by a statement that merely says they _should_ occur rather than being mandatory.

```
It must be well-formed XML.
It must validate against the relevant version of the IATI [organisation|activity] schema
```

**Comment by amy-silcock** [comment]
The Key Considerations page has now been re-written on the iatistandard website. No further work needed.
