### ISSUE TITLE
Guidance on commitments

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Guidance#26]
Building upon this from @bill-anderson

---

Commitment

For publishers reporting the same activity to the OECD Creditor Reporting System: " ..." (There is a definition)

For others, depending on business model, this is:
Total activity budget 
Total activity cost
Total contract value

For multi-funded activities this is the reporting organisation's commitment, not the sum-total including others.

The commitment should be reported at the beginning of an activity, and any subsequent adjustments should be reported (positive or negative) as adjustments to the original, not restatements of the overall total.

The sum of commitments should, at any time, reflect the total commitment for the activity.

Budget

The purpose of the budget element is to provide predictability to the recipient as to how the total financial commitment to the activity will be delivered over the agreed lifetime of the activity.

The budget element/s should reflect the total commitment broken down into annual or quarterly portions. 

While the commitment is often based on a formal, legal agreement, budgets are non-binding, indicative values. While reporting organisations cannot be held accountable for these values, they are immensely helpful to recipients' planning processes.

Planned Disbursements

The purpose of this element is to provide the recipient with predictable information about specific cash flows.

This element should only be used where information on cashflow is central to the activity (as in large-scale budget support)  or where specific agreed cash transfers are part of the contract.

**Comment by amy-silcock** [comment]
https://github.com/IATI/IATI-Guidance/issues/27
