### ISSUE TITLE
The XI-IATI changelog doesn't list all entries

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Guidance#308]
Observed via https://github.com/andylolz/org-id-finder/issues/6#issuecomment-369359614

The [changelog](https://github.com/IATI/IATI-Guidance/blob/master/en/upgrades/nonembedded-codelist-changelog.rst) for the ``XI-IATI`` codelist doesn't include the addition of ``XI-IATI-IADB``.  

There are 18 values on the current codelist, but 15 changelog items

Any idea how we can find the proposals and add the missing ones?

**Comment by andylolz** [comment]
1 found, 2 to go: https://support.iatistandard.org/hc/en-us/articles/214389786

**Comment by stevieflow** [comment]
Seems like (to me!) that @rory09 didn't update the changelog... maybe one for @rory09 to fix / add a PR?

**Comment by andylolz** [comment]
> maybe one for @rory09 to fix / add a PR?

Too late: #309.
