### ISSUE TITLE
Guidance on receiver / recipient - org

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Guidance#40]
Original Issue: https://github.com/IATI/IATI-Extra-Documentation/issues/111

In Org standard we declare:  `recipient-org`

In Activity standard, in a transaction, we declare: `receiver-org`

From @bill-anderson 

> yes, they are different
> 
> receiver should be the owner of the bank account receiving cash - not necessarily the recipient

**Comment by amy-silcock** [comment]
No further discussion has happened.
