### ISSUE TITLE
Guidance on best practice on transactions / budget aggregation

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Guidance#42]
Moved from: https://github.com/IATI/IATI-Extra-Documentation/issues/33#issuecomment-41028137

@bill-anderson:

I think documenting best practice like this is over complicated and confusing. Propose we keep this simple.

Best practice (and minimum ask) on aggregation is:
Transactions - monthly (quarterly)
Budgets - annual in line with recipient fiscal year, or quarterly (annual)

Guidance should be that new publishers aim for best practice on current data (NB not current activities) and stick to that moving forward. Earlier data on current activities is a "publish what you can" issue.

I am not persuaded that sticking to this over a period of time runs into big data problems. IATI data is generally not very big.

**Comment by amy-silcock** [comment]
No further discussion has happened.
