### ISSUE TITLE
FAQ s- Review & Move The Contents of Knowledge Base Articles to FAQs

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Guidance#57]
The contents of the following knowledge base articles need to be reviewed and any valid content moved into the online FAQs:
http://support.iatistandard.org/entries/20030801-Do-I-need-to-understand-XML-
http://support.iatistandard.org/entries/20029627-What-is-XML-It-looks-scary-
http://support.iatistandard.org/entries/20031943-What-is-a-schema-
http://support.iatistandard.org/entries/20031763-What-does-IATI-data-look-like-

**Comment by amy-silcock** [comment]
Guidance around xml and IATI can now be found on the IATI website: https://iatistandard.org/en/
