### ISSUE TITLE
Missing Link: Establishing Publishing Policies: Implementation Schedule

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Guidance#64]
Suggest including a link to the Implementation schedule for donors, there is currently only one for NGOs/CSOs

http://iatistandard.org/how-to-publish/establish-publishing-policies/

> The Implementation Schedule

**Comment by amy-silcock** [comment]
Implementation schedule no longer exists. Current guidance is here: https://iatistandard.org/en/guidance/preparing-organisation/organisation-data-publication/
