### ISSUE TITLE
Thresholds - clarity needed

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Guidance#66]
3rd paragraph, should include that these should be published IN IMPLEMENTATION SCHEDULES, this isn't clear from current text, and should it also be included in registry records?

http://iatistandard.org/how-to-publish/establish-publishing-policies/

**Comment by amy-silcock** [comment]
Instructions are now here: https://iatistandard.org/en/guidance/preparing-organisation/organisation-data-publication/
