### ISSUE TITLE
Establishing Publishing Policies: Exclusions

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Guidance#67]
If exclusions should also be published in the implementation schedule, as well as the registry record, this needs to be included. 

http://iatistandard.org/how-to-publish/establish-publishing-policies/

> However IATI requires that the policy of how those exclusions are made is made public, as part of the Registry Record in order to provide context to those who are using the data.

**Comment by amy-silcock** [comment]
Instructions can now be found here: https://iatistandard.org/en/guidance/preparing-organisation/organisation-data-publication/information-and-data-you-cant-publish-exclusions/
