### ISSUE TITLE
Establishing Publishing Policies: Which Aid Activities Should be Included?

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Guidance#68]
I think the link to the code list is fairly inaccessible, I would recommend listing them as well linking to the codelist.
http://iatistandard.org/how-to-publish/establish-publishing-policies/

> Information can be published about any activity which falls under any of the aid categories as defined at http://iatistandard.org/codelists/flow_type/ .

**Comment by amy-silcock** [comment]
No further discussion
