### ISSUE TITLE
Establishing Publishing Policies: Licensing

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Guidance#69]
There is a lot of information here on licensing, that might be served best on another page, or linked through somehow, as it distracts from the flow of the rest of the guidance a little. It might be worth extracting it as a separate page? 
http://iatistandard.org/how-to-publish/establish-publishing-policies/

**Comment by amy-silcock** [comment]
Licensing information can now be found here: https://iatistandard.org/en/guidance/preparing-organisation/organisation-data-publication/how-to-license-your-data/
