### ISSUE TITLE
Data Considerations - include link to implementation schedule

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Guidance#70]
In the introductory paragraph, I suggest adding a link to the Implementation Schedule section http://iatistandard.org/how-to-publish/select-data-to-publish/

> Deciding what data to publish can be aided by filling out the organisation and Activity tabs of the Implementation Schedule.

**Comment by amy-silcock** [comment]
Instructions on how to publish are now on the IATI website: https://iatistandard.org/en/guidance/publishing-data/publishing-checklist/ Implementation schedule no longer exists.
