### ISSUE TITLE
Clarify language - Data Considerations

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Guidance#71]
In the title for the DFID Requirements section, I would state " relevant for UK NGOs and their partners" rather than just NGOs and their partners. Makes it a bit clearer

http://iatistandard.org/how-to-publish/select-data-to-publish/

> DFID Minimum Requirements (UK NGOs and their Partners)

**Comment by amy-silcock** [comment]
No longer an issue. Equivalent page is here: https://iatistandard.org/en/guidance/preparing-data/donors-reporting-requirements/
