### ISSUE TITLE
Produce Your Datafiles: Establish a Change Control Procedure

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Guidance#72]
http://iatistandard.org/how-to-publish/create-datafiles/

This is slightly unclear, and might work better with a little more detail. For example, suggest recording the information, and ways it can be done.

> Establish a change control procedure

**Comment by amy-silcock** [comment]
This is now captured here: https://iatistandard.org/en/guidance/publishing-data/creating-files/how-to-create-your-iati-data-files/
