### ISSUE TITLE
Produce Your Datafiles: Data Quality Control

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Guidance#73]
This could be strengthened a little by adding examples of the way this could be done: peer review by colleagues, or possibly an individual responsible for checking it in the case of organisations publishing a lot of information, or automated?

http://iatistandard.org/how-to-publish/create-datafiles/

> Data Quality Control

**Comment by amy-silcock** [comment]
There's now a section about data quality on the IATI website: https://iatistandard.org/en/guidance/publishing-data/data-quality/
