### ISSUE TITLE
Publish Your Data: Validate Your IATI Files Using the IATI Validator

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Guidance#74]
It might be useful to include an N.B. here that says this is a different step from data quality checking, the validator is only about ensuring the XML is correct and is not a measure of the quality of the data.

http://iatistandard.org/how-to-publish/publish-files/

**Comment by amy-silcock** [comment]
Website currently asks organisations to validate their files before publishing: https://iatistandard.org/en/guidance/publishing-data/publishing-checklist/
