### ISSUE TITLE
Publish Your Data: Step 4 Add Details of your datafiles

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Guidance#75]
The link to the CSV upload is broken

http://iatistandard.org/how-to-publish/publish-files/

> Once your publisher account has been authorised, log into it and select the ‘Add Datafile’ option in order to add the details and URL location of your IATI datafiles that you are publishing. If you have a lot of datafiles’ details to add you can instead add the details to a CSV file which can be imported to the Registry to add the files in bulk. The template and other information for using the CSV file is at http://www.iatiregistry.org/csv/upload .

**Comment by amy-silcock** [comment]
The equivalent page is now here: https://iatistandard.org/en/guidance/publishing-data/publishing-files/how-to-publish-your-data-on-the-iati-registry-/
