### ISSUE TITLE
CSV mentioned in section where people might not be using CSVs

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Guidance#78]
http://dev.iatistandard.org/guidance/how-to-publish/publish-files
"original input CSV file data" - not sure this should say CSV here. I think this is assuming people are using CSV2IATI, but people may be looking at this section after having used aidstream etc.

**Comment by amy-silcock** [comment]
This is no longer an issues. Equivalent page is now here: https://iatistandard.org/en/guidance/publishing-data/publishing-files/how-to-publish-your-data-on-the-iati-registry-/
