### ISSUE TITLE
"CSV Converter" or "CSV2IATI"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Guidance#89]
http://dev.iatistandard.org/guidance/how-to-publish/select-publishing-tool

**Comment by amy-silcock** [comment]
CSV2IATI has been decommissioned. The publishing tool page has been re-written on the new website: https://iatistandard.org/en/guidance/publishing-data/creating-files/publishing-tools-and-services-to-create-your-iati-data-files/
